[package]
name = "mqtt-saver"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.14.0"
chrono = "0.4.0"
log = "0.4.0"
env_logger = "0.9.0"
